package com.txtled.ellia_r.bean.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.txtled.ellia_r.bean.ColorList;

import com.txtled.ellia_r.bean.dao.ColorListDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig colorListDaoConfig;

    private final ColorListDao colorListDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        colorListDaoConfig = daoConfigMap.get(ColorListDao.class).clone();
        colorListDaoConfig.initIdentityScope(type);

        colorListDao = new ColorListDao(colorListDaoConfig, this);

        registerDao(ColorList.class, colorListDao);
    }
    
    public void clear() {
        colorListDaoConfig.clearIdentityScope();
    }

    public ColorListDao getColorListDao() {
        return colorListDao;
    }

}
